### ISSUE TITLE
Немогу запустить код из примера

### ISSUE THREAD

**Issue by shared-object** [aiogram/aiograph#11]
При запуске кода из примера выдает ошибку:

```python
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test.py", line 3, in <module>
    from aiograph import Telegraph
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiograph/__init__.py", line 1, in <module>
    from . import types
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiograph/types/__init__.py", line 6, in <module>
    from .page_list import PageList
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiograph/types/page_list.py", line 13, in <module>
    class PageList(TelegraphObject):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiograph/types/page_list.py", line 21, in PageList
    pages: List[Page] = ib(factory=list, convert=pages_converter)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attrib() got an unexpected keyword argument 'convert'```

**Comment by alteralt** [comment]
Look at https://github.com/aiogram/aiograph/issues/3
